name: Automate FSBO Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every day at midnight (UTC)
  workflow_dispatch:  # Manually trigger the workflow if needed

jobs:
  scraper:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client requests beautifulsoup4 gspread_dataframe jupyter papermill

      - name: Write credentials.json from secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run the FSBO scraper
        run: python fsbo_scraper.py
